### ISSUE TITLE
feature/coder2 branch goals

### ISSUE THREAD

**Issue by ynnadrules** [andriydruk/swift-java#1]
Hi!

I just had a question about the [feature/coder2](https://github.com/readdle/swift-java/tree/feature/coder2) branch.

1.  is still relevant?
1.  is its goal to remove `java_swift` as a dependency completely? 

Thanks!

**Comment by andriydruk** [comment]
Hi

1. Yes, `feature/coder2 ` is still in progress
We now working on Swift 5 toolchain with aarch64, after it will be completed I'm going to continue working on Coder2

2. Yes, one of the main goals is to remove `java_swift` dependency. Also, we wanna move `JNI_OnLoad` to annotation processor generated code.  It will give us the ability to generate a map of all SwiftValue classes and improve encoding and decoding abstract arrays

**Comment by ynnadrules** [comment]
Sounds good, thanks!
